# Generated by Django 3.0.8 on 2020-07-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Project Avatar', upload_to='avatars/projects'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', upload_to='avatars/users'),
        ),
    ]
