# Generated by Django 3.0.8 on 2020-08-04 02:15

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Project Avatar', upload_to='avatars/projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_ticket_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='color',
            field=colorful.fields.RGBColorField(default='#0000FF'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to='task_management.Profile'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_in_project',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='task_management.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='color',
            field=colorful.fields.RGBColorField(default='#0000FF'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='task_management.AttributeType'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='ticket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='task_management.Ticket'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', upload_to='avatars/users'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='task_management.State'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
