# Generated by Django 3.0.8 on 2020-07-30 21:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Project Avatar', upload_to='avatars/projects'),
        ),
        migrations.AddField(
            model_name='state',
            name='color',
            field=colorfield.fields.ColorField(default='9f60c8', max_length=18),
        ),
        migrations.AddField(
            model_name='type',
            name='color',
            field=colorfield.fields.ColorField(default='5c82ab', max_length=18),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Profile picture', upload_to='avatars/users'),
        ),
    ]
