# Generated by Django 3.0.8 on 2020-07-13 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettemplate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tickettemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='project',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_template', to='task_management.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(max_length=50)),
                ('ticket_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='task_management.TicketTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.TextField(max_length=50)),
                ('ticket_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='task_management.TicketTemplate')),
            ],
        ),
    ]
