# Generated by Django 3.0.8 on 2020-08-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20200803_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='max_ticket_id',
        ),
    ]
