# Generated by Django 3.0.8 on 2020-08-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_project_max_ticket_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='state',
            name='position',
            field=models.IntegerField(default=-1),
        ),
    ]
